# Generated by Django 5.0.1 on 2024-12-20 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods', models.CharField(max_length=30, verbose_name='Название')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('condition', models.CharField(choices=[('новый', 'новый'), ('используемый', 'используемый'), ('сломанный', 'сломанный')], max_length=20, verbose_name='Состояние')),
            ],
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Request', models.CharField(max_length=1600, verbose_name='ОТЗЫВ')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
