# Generated by Django 5.0.1 on 2024-12-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='User',
            field=models.CharField(max_length=16, verbose_name='ИМЯ'),
        ),
    ]
