# Generated by Django 5.0.1 on 2024-12-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_applications_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='User',
            field=models.CharField(max_length=100),
        ),
    ]
