# Generated by Django 5.0.1 on 2024-12-21 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_user_applications_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='Request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.goods'),
        ),
    ]
