# Generated by Django 5.0.1 on 2024-12-22 17:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_users_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='Request_count',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='users',
            name='Rent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.goods'),
        ),
    ]
