# Generated by Django 5.1.4 on 2024-12-24 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_users_count_alter_applications_request_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Rent',
            field=models.ForeignKey(default='-----', null=True, on_delete=django.db.models.deletion.PROTECT, to='main.goods'),
        ),
    ]
