# Generated by Django 5.0.1 on 2025-01-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_users_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='rented_count',
            field=models.IntegerField(default=0, verbose_name='Взято'),
        ),
    ]
