# Generated by Django 5.0.1 on 2025-01-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_users_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='User',
            field=models.CharField(max_length=100),
        ),
    ]
