# Generated by Django 5.0.1 on 2025-01-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_users_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Plus',
            field=models.BooleanField(default=False),
        ),
    ]
