# Generated by Django 5.0.1 on 2025-01-11 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_item_supplier_alter_users_plus_purchaseplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseplan',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_plans', to='main.goods'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='description',
            field=models.CharField(default=12, max_length=1023),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
