# Generated by Django 5.0.1 on 2025-01-11 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_purchaseplan_item_supplier_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseplan',
            options={'verbose_name': 'План закупки', 'verbose_name_plural': 'Планы закупок'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'Поставщик', 'verbose_name_plural': 'Поставщики'},
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='description',
        ),
        migrations.AddField(
            model_name='purchaseplan',
            name='count',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='purchaseplan',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_plans', to='main.goods', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='purchaseplan',
            name='planned_date',
            field=models.DateField(verbose_name='Планируемая дата'),
        ),
        migrations.AlterField(
            model_name='purchaseplan',
            name='planned_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Планируемая цена'),
        ),
        migrations.AlterField(
            model_name='purchaseplan',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.supplier', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Поставщик'),
        ),
    ]
