# Generated by Django 5.0.1 on 2025-03-16 07:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_applications_repair_request_alter_goods_goods_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods', models.CharField(max_length=20, null=True, verbose_name='Состояние')),
                ('count', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('rented_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Взято')),
            ],
            options={
                'verbose_name': 'Инвентарь',
                'verbose_name_plural': 'Инвентарь',
            },
        ),
        migrations.DeleteModel(
            name='Goods',
        ),
    ]
