# Generated by Django 5.0.1 on 2025-01-11 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_applications_options_alter_goods_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': 'Инвентарь', 'verbose_name_plural': 'Инвентарь'},
        ),
    ]
