# Generated by Django 5.0.1 on 2025-01-11 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_applications_repair_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications_get',
            name='Request',
            field=models.ForeignKey(db_column='Предмет', null=True, on_delete=django.db.models.deletion.PROTECT, to='main.goods'),
        ),
        migrations.AlterField(
            model_name='applications_repair',
            name='Request',
            field=models.ForeignKey(db_column='Предмет', null=True, on_delete=django.db.models.deletion.PROTECT, to='main.goods'),
        ),
    ]
