# Generated by Django 5.0.1 on 2025-01-11 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_applications_get_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications_get',
            name='Request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.goods', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='applications_get',
            name='username',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='applications_repair',
            name='username',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
    ]
