# Generated by Django 5.0.1 on 2025-01-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_goods_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Добавлено'),
        ),
        migrations.AddField(
            model_name='goods',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='goods',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
