# Generated by Django 5.0.1 on 2025-01-21 13:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_goods_created_at_goods_description_goods_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Добавлено'),
        ),
    ]
